# fly.toml app configuration file generated for project-auro-dev-wispy-water-6592 on 2024-03-16T16:07:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'project-auro-dev-wispy-water-6592'
primary_region = 'arn'

[build]
  dockerfile = '.devcontainer/Dockerfile'
  build-target = 'astro'

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
