# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-deployment
  labels:
    app: astro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astro
  template:
    metadata:
      labels:
        app: astro
    spec:
      containers:
        - name: astro
          image: hortasha/project-auro:astro-dev
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: dockerhub-cred

---
apiVersion: v1
kind: Service
metadata:
  name: astro-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: astro
