// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.assetcategory */
type Assetcategory = 
  | 'avatar'
  | 'weapon'
  | 'armor'
  | 'accessory'
  | 'consumable'
  | 'item'
  | 'icon'
  | 'companion'
  | 'structure'
  | 'currency';

export default Assetcategory;
