// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountId } from './Account';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.auth */
export default interface AuthTable {
  accountId: ColumnType<AccountId, AccountId, AccountId>;

  refreshTokenHash: ColumnType<string | null, string | null, string | null>;

  refreshTokenExpires: ColumnType<Date | null, Date | string | null, Date | string | null>;

  accessTokenHash: ColumnType<string | null, string | null, string | null>;

  accessTokenExpires: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Auth = Selectable<AuthTable>;

export type NewAuth = Insertable<AuthTable>;

export type AuthUpdate = Updateable<AuthTable>;
