// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.itemtype */
type Itemtype = 
  | 'weapon'
  | 'armor'
  | 'accessory'
  | 'consumable'
  | 'item'
  | 'companion'
  | 'structure';

export default Itemtype;
