// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as Itemtype } from './Itemtype';
import type { AssetId } from './Asset';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.item */
export type ItemId = string & { __brand: 'ItemId' };

/** Represents the table public.item */
export default interface ItemTable {
  id: ColumnType<ItemId, ItemId | undefined, ItemId>;

  name: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  type: ColumnType<Itemtype, Itemtype, Itemtype>;

  assetId: ColumnType<AssetId, AssetId, AssetId>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Item = Selectable<ItemTable>;

export type NewItem = Insertable<ItemTable>;

export type ItemUpdate = Updateable<ItemTable>;
