// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AssetId } from './Asset';
import type { ServerId } from './Server';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.location */
export type LocationId = string & { __brand: 'LocationId' };

/** Represents the table public.location */
export default interface LocationTable {
  id: ColumnType<LocationId, LocationId | undefined, LocationId>;

  name: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  available: ColumnType<boolean, boolean | undefined, boolean>;

  assetId: ColumnType<AssetId, AssetId, AssetId>;

  serverId: ColumnType<ServerId, ServerId, ServerId>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Location = Selectable<LocationTable>;

export type NewLocation = Insertable<LocationTable>;

export type LocationUpdate = Updateable<LocationTable>;
