// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as AssetTable } from './Asset';
import type { default as ServerTable } from './Server';
import type { default as AccountTable } from './Account';
import type { default as AuthTable } from './Auth';
import type { default as UserTable } from './User';
import type { default as SkillTable } from './Skill';
import type { default as UserSkillTable } from './UserSkill';
import type { default as KyselyMigrationTable } from './KyselyMigration';
import type { default as KyselyMigrationLockTable } from './KyselyMigrationLock';
import type { default as ItemTable } from './Item';
import type { default as UserItemTable } from './UserItem';
import type { default as CurrencyTable } from './Currency';
import type { default as UserCurrencyTable } from './UserCurrency';
import type { default as LocationTable } from './Location';

export default interface PublicSchema {
  'public.asset': AssetTable;

  'public.server': ServerTable;

  'public.account': AccountTable;

  'public.auth': AuthTable;

  'public.user': UserTable;

  'public.skill': SkillTable;

  'public.userSkill': UserSkillTable;

  'public.kyselyMigration': KyselyMigrationTable;

  'public.kyselyMigrationLock': KyselyMigrationLockTable;

  'public.item': ItemTable;

  'public.userItem': UserItemTable;

  'public.currency': CurrencyTable;

  'public.userCurrency': UserCurrencyTable;

  'public.location': LocationTable;
}
