// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.skill */
export type SkillId = string & { __brand: 'SkillId' };

/** Represents the table public.skill */
export default interface SkillTable {
  id: ColumnType<SkillId, SkillId | undefined, SkillId>;

  name: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Skill = Selectable<SkillTable>;

export type NewSkill = Insertable<SkillTable>;

export type SkillUpdate = Updateable<SkillTable>;
