// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountId } from './Account';
import type { ServerId } from './Server';
import type { default as Usertype } from './Usertype';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.user */
export type UserId = string & { __brand: 'UserId' };

/** Represents the table public.user */
export default interface UserTable {
  id: ColumnType<UserId, UserId | undefined, UserId>;

  name: ColumnType<string | null, string | null, string | null>;

  accountId: ColumnType<AccountId, AccountId, AccountId>;

  actions: ColumnType<number, number | undefined, number>;

  serverId: ColumnType<ServerId, ServerId, ServerId>;

  type: ColumnType<Usertype, Usertype | undefined, Usertype>;

  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type User = Selectable<UserTable>;

export type NewUser = Insertable<UserTable>;

export type UserUpdate = Updateable<UserTable>;
