// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.usertype */
type Usertype = 
  | 'admin'
  | 'player';

export default Usertype;
