// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.user_currency */
export default interface UserCurrencyTable {
  userId: ColumnType<string | null, string | null, string | null>;

  currencyId: ColumnType<string | null, string | null, string | null>;

  amount: ColumnType<number, number | undefined, number>;

  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type UserCurrency = Selectable<UserCurrencyTable>;

export type NewUserCurrency = Insertable<UserCurrencyTable>;

export type UserCurrencyUpdate = Updateable<UserCurrencyTable>;
