// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.user_item */
export type UserItemId = string & { __brand: 'UserItemId' };

/** Represents the table public.user_item */
export default interface UserItemTable {
  id: ColumnType<UserItemId, UserItemId | undefined, UserItemId>;

  userId: ColumnType<string | null, string | null, string | null>;

  itemId: ColumnType<string | null, string | null, string | null>;

  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type UserItem = Selectable<UserItemTable>;

export type NewUserItem = Insertable<UserItemTable>;

export type UserItemUpdate = Updateable<UserItemTable>;
