// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.user_skill */
export default interface UserSkillTable {
  userId: ColumnType<string | null, string | null, string | null>;

  skillId: ColumnType<string | null, string | null, string | null>;

  xp: ColumnType<number, number | undefined, number>;

  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type UserSkill = Selectable<UserSkillTable>;

export type NewUserSkill = Insertable<UserSkillTable>;

export type UserSkillUpdate = Updateable<UserSkillTable>;
