name: Deploy to AKS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to. Defaults to test.
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
        default: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ vars.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ vars.SUBSCRIPTION_ID }}","tenantId":"${{ vars.TENANT_ID }}"}'

      - name: Install kubectl
        run: az aks install-cli

      - name: Get AKS credentials
        run: |
          az aks get-credentials --name aks-projectauro-${{github.event.inputs.environment}} --resource-group rg-projectauro-${{github.event.inputs.environment}}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml
