name: Setup Fly

on:
  workflow_dispatch:

jobs:
  create-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: fly deploy --access-token ${{ secrets.FLY_API_TOKEN }}
